<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>BackOff</title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<link href="https://fonts.googleapis.com/css?family=Days+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Palanquin+Dark&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="../css/normalize.css">
	<link rel="stylesheet" href="../css/style.css">
	<script src="../js/script.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	
</head>
<body class="logphp">

	<h1>Interface d'administration</h1>

		<p class="pres">Projet d'interface d'administration que j'ai réalisé lors de mon stage en entreprise.<br> Ceci est un tableau info Clients. Il regroupe les différents clients de l'entreprise.<br> Je peux donc ajouter un client, le supprimer, l'éditer et ajouter de nouveaux champs.<br>Dans ce projet nous retrouvons du PHP/SQL mais aussi du JAVASCRIPT.</p>

	<div class="login-page">

		<p class="image">
			<img src="../img/ordi.png">
		</p>

  	<div class="form">
    	
    	<form class="login-form formulaire" method="POST">

      		<input type="text" placeholder="username" name="username" />

      		<input type="password" placeholder="password" name="password" />

      		<button>login</button>

   	 	</form>

  	</div>

	</div>

</body>

</html>